import React from "react";
import { useEffect } from "react";
import styles from "../styles/profile.module.css";

import IconLabel from "./components/IconLabel";

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faEnvelope,faSchool,faCheckCircle,faLock,faBoltLightning,faClock,faCalendar,faClockRotateLeft,faIdBadge,faRoad } from "@fortawesome/free-solid-svg-icons";

import swal from "sweetalert";

import moment from "moment";

import Head from 'next/head';
import 'bootstrap/dist/css/bootstrap.css';



export default function UserProfile(): JSX.Element {
  const [profile, setProfile] = React.useState<any>("");
  useEffect(() => {
    fetch("/api/profile")
    .then((res: any)=>res.json())
    .then((profile: any) => {
      setProfile(profile);
      // stores the jsx properties into the "profile" obj
      profile["strandGradesJSX"] = Object.keys(profile.strandGrades).map((item:any)=>
        <tr key={item}>
          <td>{item}</td>
          <td>{profile.strandGrades[item]}</td>
        </tr>
      );
    })
    .catch((err)=>{
      // Sweetalert dialog fires when the profile fails to load
      swal({title: "Unable to retrieve profile",text: "We were unable to retrieve the profile 😢",icon: "error"});
    });
  }, []);

  return (
  <div className={styles.body}>
    <Head>
      <title>{profile.displayName} - Profile</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className={styles.mainCard}>
      <header className={styles.header}>
        <img className={styles.profilePhoto} src={(profile.photoUrl!=null && profile.photoUrl.length>0)?profile.photoUrl:"./profile_pic.png"} alt="" />
        <h2 style={{margin:"10px 0px"}}>{profile.displayName}</h2>
        <IconLabel value={profile.email} icon={faEnvelope}></IconLabel>
        <IconLabel value={profile.schoolName} icon={faSchool} verified={profile.schoolVerified}></IconLabel>
        <br></br>
        <IconLabel fontSize={12} title={"Date Joined"} value={new Date(profile.created).toLocaleString()} icon={faCalendar}></IconLabel>
        <IconLabel fontSize={12} title={"Last Active"} value={new Date(profile.created).toLocaleString()} icon={faClock}></IconLabel>
      </header>
      <main className={styles.main}>
        <IconLabel value={profile.superPower} title={"Super Power: "} icon={faBoltLightning}></IconLabel>
        <IconLabel value={profile.currentStrandPath} title={"Current Strand Path: "} icon={faRoad}></IconLabel>
        <br></br>
        <h4>Strand Grades</h4>
        <br></br>
        {
          (profile.shareStatistics) ? (<table style={{
            width:"50%",
            }} className="table table-bordered bg-light text-dark">
            <tbody>
            {
              profile.strandGradesJSX
            }
            </tbody>
          </table>) : (<div style={{display:"flex",flexDirection:"row",alignItems:"center",width:"50%"}} className="stats alert alert-info">
          <FontAwesomeIcon icon={faLock}></FontAwesomeIcon>
          <p style={{textDecoration:"italic",marginLeft:10,marginTop:0,marginBottom:0}}>This user chose to keep their stats private.</p>
        </div>)
        }
        <br></br>
      </main>
    </div>
  </div>
  );
}
